### ISSUE TITLE
Node v6 support -- change gulp-xml-editor => gulp-xml-transformer

### ISSUE THREAD

**Issue by anandthakker** [developmentseed/collecticons-processor#12]
See https://github.com/morou/gulp-xml-editor/issues/14#issuecomment-227106186

**Comment by anandthakker** [comment]
And actually, fwiw: the libxmljs dependency is pretty heavy/annoying at installation time -- I wonder if there's a quicker/easier way to implement [stripGrid](https://github.com/developmentseed/collecticons-processor/blob/master/src/index.js#L230-L238) that doesn't require full-on xml parsing...?

**Comment by anandthakker** [comment]
I just hit this again.  Ping @danielfdsilva

**Comment by danielfdsilva** [comment]
It's on my list! I want to hit this as soon as this workload lightens.
